### ISSUE TITLE
Add a "Back to main site" link

### ISSUE THREAD

**Issue by artlogic** [nsbasic/volt-docs#35]
There are a lot of ways to do this and I'm not sure which fits in best with the design, but we'll eventually need a link that takes you back to the main site. I'm not sure what the verbiage should be or where it should be positioned.

It may be a good idea to consider how to add these to other properties - the API docs, the Client docs, the Dashboard, etc...

**Comment by SKBruck** [comment]
Do you want a link that goes back to main, or do you want a breadcrumb situation?

**Comment by artlogic** [comment]
I don't believe breadcrumbs are necessary since there isn't a deep hierarchy here. The idea was a link that takes to back to the main site, which will eventually be more than a landing page. Might be good to see how other people do this.

**Comment by SKBruck** [comment]
I don't want to commit changes for this without clearance, so I'm attaching a screenshot of what I've done. In this case, I just added a simple link to the /_layouts/post.html, but there are likely other solutions - this was just the quickest. I chose to place it above the post because that's pretty standard on other pages, as is the simple verbiage.

![back-to-home](https://cloud.githubusercontent.com/assets/2489779/25934419/b0f0b350-35eb-11e7-92ba-201642cd0ab9.png)

**Comment by artlogic** [comment]
It's a good thing you checked. The intention of this wasn't a back to home link. It's a back to the main site from a sub site.

**Comment by SKBruck** [comment]
I misunderstood - this may be something we should talk about in person so I can better understand what you're asking for and why you want it so I can get a better idea for how to incorporate it into the site.

**Comment by artlogic** [comment]
That's fine. We can talk about it when we meet next. Please add it to the agenda.

**Comment by SKBruck** [comment]
Added to the agenda.

**Comment by artlogic** [comment]
Docs are going away - closing.
